import json

F = "math"
# (id, name, level, description, [shrubs: (id, name, level, description)])
TREES = [
    ("fractions_decimals", "Fractions & Decimals", 1, "Ways to describe parts of a whole.", [
        ("equivalent_fractions", "Equivalent Fractions", 1, "Different-looking fractions that mean the same amount."),
        ("fraction_operations", "Operations on Fractions", 1, "Adding, subtracting, multiplying and dividing fractions."),
        ("decimals_percents", "Decimals & Percents", 1, "Writing parts of a whole in base ten or out of 100."),
    ]),
    ("ratios_proportions", "Ratios & Proportions", 1, "Comparing quantities and scaling them up or down together.", [
        ("unit_rates", "Unit Rates", 1, "How much of one thing per single unit of another."),
        ("proportional_relationships", "Proportional Relationships", 2, "Two quantities that always grow by the same factor."),
        ("percent_change", "Percent Change", 2, "Describing increases and decreases as a percent."),
    ]),
    ("exponents_roots", "Exponents & Roots", 1, "Repeated multiplication, and how to undo it.", [
        ("exponent_rules", "Exponent Rules", 2, "Shortcuts for multiplying, dividing and raising powers."),
        ("scientific_notation", "Scientific Notation", 2, "Writing huge and tiny numbers as a number times a power of ten."),
        ("square_roots_radicals", "Square Roots & Radicals", 2, "Finding the number that multiplies by itself to give another."),
    ]),
    ("variables_expressions", "Variables & Expressions", 1, "Using letters to stand for numbers you don't know yet.", [
        ("order_of_operations", "Order of Operations", 1, "The agreed order for evaluating an expression."),
        ("distributive_property", "Distributive Property", 1, "Multiplying a number across everything inside parentheses."),
        ("combining_like_terms", "Combining Like Terms", 1, "Simplifying expressions by grouping matching pieces."),
    ]),
    ("sets_logic", "Sets & Logic", 1, "Grouping things and reasoning with true-or-false statements.", [
        ("sets_venn", "Sets & Venn Diagrams", 1, "Collections of objects and how they overlap."),
        ("logical_statements", "Logical Statements", 2, "Combining true/false claims with and, or, not, and if-then."),
        ("mathematical_proof", "Mathematical Proof", 3, "Building an argument that shows something is always true."),
    ]),
    ("linear_equations", "Linear Equations", 2, "Finding the unknown value that keeps an equation balanced.", [
        ("multistep_equations", "Solving Multi-Step Equations", 2, "Undoing operations step by step to isolate a variable."),
        ("linear_inequalities", "Linear Inequalities", 2, "Finding all the values that make a comparison true."),
        ("literal_equations", "Rearranging Formulas", 2, "Solving a formula for a different variable."),
    ]),
    ("functions", "Functions", 2, "Rules that turn each input into exactly one output.", [
        ("function_notation", "Function Notation", 2, "Writing f(x) to name a rule and its input."),
        ("domain_range", "Domain & Range", 2, "Which inputs a function accepts and which outputs it can give."),
        ("function_transformations", "Transforming Functions", 3, "Shifting, stretching and flipping graphs."),
        ("function_composition", "Composing Functions", 3, "Feeding one function's output into another."),
        ("inverse_functions", "Inverse Functions", 3, "A function that undoes another function."),
    ]),
    ("linear_functions", "Linear Functions", 2, "Relationships that change at a constant rate and graph as lines.", [
        ("slope", "Slope", 2, "How steep a line is: rise over run."),
        ("slope_intercept_form", "Slope-Intercept Form", 2, "Writing a line as y = mx + b."),
    ]),
    ("triangles", "Triangles & Angles", 2, "Shapes and angle facts that geometry is built on.", [
        ("angle_relationships", "Angle Relationships", 1, "Supplementary, vertical and parallel-line angles."),
        ("pythagorean_theorem", "Pythagorean Theorem", 2, "a² + b² = c² for right triangles."),
        ("similar_triangles", "Similar Triangles", 2, "Same shape, different size, with proportional sides."),
        ("triangle_congruence", "Triangle Congruence", 3, "Proving two triangles are exact copies."),
    ]),
    ("statistics", "Statistics", 2, "Summarizing and making sense of data.", [
        ("mean_median_mode", "Mean, Median & Mode", 1, "Different ways to find the center of a data set."),
        ("spread_std_dev", "Standard Deviation & Spread", 3, "Measuring how spread out the data is."),
        ("scatter_plots_correlation", "Scatter Plots & Correlation", 3, "Spotting relationships between two variables."),
        ("normal_distribution", "Normal Distribution", 4, "The bell curve and why so much data follows it."),
    ]),
    ("probability", "Probability", 2, "Measuring how likely something is to happen.", [
        ("basic_probability", "Basic Probability", 2, "Favorable outcomes divided by possible outcomes."),
        ("counting_combinatorics", "Permutations & Combinations", 3, "Counting arrangements and selections without listing them."),
        ("conditional_probability", "Conditional Probability", 3, "How likely A is once you know B happened."),
        ("bayes_theorem", "Bayes' Theorem", 4, "Updating a belief when new evidence arrives."),
    ]),
    ("systems_of_equations", "Systems of Equations", 3, "Finding values that satisfy several equations at once.", [
        ("substitution_method", "Substitution Method", 3, "Solving one equation and plugging it into another."),
        ("elimination_method", "Elimination Method", 3, "Adding equations together to cancel a variable."),
    ]),
    ("polynomials", "Polynomials", 3, "Expressions built from powers of a variable.", [
        ("polynomial_arithmetic", "Adding & Multiplying Polynomials", 3, "Combining polynomials into one expression."),
        ("factoring", "Factoring", 3, "Breaking a polynomial into pieces that multiply together."),
    ]),
    ("quadratic_functions", "Quadratic Functions", 3, "Functions with an x² term that graph as parabolas.", [
        ("parabolas", "Graphing Parabolas", 3, "The U-shaped graph, its vertex and its axis."),
        ("completing_the_square", "Completing the Square", 3, "Rewriting a quadratic to reveal its vertex."),
        ("quadratic_formula", "Quadratic Formula", 3, "A formula that solves any quadratic equation."),
    ]),
    ("coordinate_geometry", "Coordinate Geometry", 3, "Describing shapes with points on a grid.", [
        ("distance_formula", "Distance Formula", 3, "The length between two points."),
        ("midpoint_formula", "Midpoint Formula", 3, "The point exactly halfway between two points."),
        ("circle_equations", "Equations of Circles", 3, "Describing a circle with an equation."),
    ]),
    ("exponential_functions", "Exponential Functions", 3, "Quantities that multiply by the same factor each step.", [
        ("growth_decay", "Exponential Growth & Decay", 3, "Populations, viruses and radioactive decay."),
        ("compound_interest", "Compound Interest", 3, "How money grows when interest earns interest."),
    ]),
    ("sequences_series", "Sequences & Series", 3, "Ordered lists of numbers and their sums.", [
        ("arithmetic_sequences", "Arithmetic Sequences", 3, "Lists that add the same amount each step."),
        ("geometric_sequences", "Geometric Sequences", 3, "Lists that multiply by the same amount each step."),
        ("sigma_notation", "Sigma Notation", 3, "A compact way to write long sums."),
    ]),
    ("logarithms", "Logarithms", 4, "Asking what power gives a number; the inverse of exponents.", [
        ("log_rules", "Properties of Logarithms", 4, "Rules for combining and splitting logs."),
        ("natural_log", "e and the Natural Log", 4, "The special number e and its logarithm."),
        ("solving_exponential_equations", "Solving Exponential Equations", 4, "Using logs to bring a variable down from an exponent."),
    ]),
    ("trigonometry", "Trigonometry", 4, "Connecting angles to side lengths and to circles.", [
        ("right_triangle_trig", "Sine, Cosine & Tangent", 3, "Side ratios in right triangles."),
        ("radians", "Radians", 4, "Measuring angles by arc length."),
        ("unit_circle", "Unit Circle", 4, "Extending sine and cosine to any angle."),
        ("trig_identities", "Trig Identities", 4, "Equations that are true for every angle."),
    ]),
    ("vectors", "Vectors", 4, "Quantities with both a size and a direction.", [
        ("vector_addition", "Vector Addition", 4, "Combining vectors tip to tail."),
        ("scalar_multiplication", "Scalar Multiplication", 4, "Stretching or shrinking a vector."),
        ("vector_magnitude", "Magnitude of a Vector", 4, "How long a vector is."),
        ("dot_product", "Dot Product", 4, "A number that measures how much two vectors point the same way."),
    ]),
    ("matrices", "Matrices", 4, "Grids of numbers for organizing and transforming data.", [
        ("matrix_operations", "Adding & Scaling Matrices", 4, "Entry-by-entry matrix arithmetic."),
        ("matrix_multiplication", "Matrix Multiplication", 4, "Combining matrices row by column."),
        ("determinants", "Determinants", 5, "A single number that says how a matrix stretches space."),
        ("matrix_inverse", "Matrix Inverse", 5, "The matrix that undoes another matrix."),
    ]),
    ("derivatives", "Derivatives", 5, "The instantaneous rate of change of a function.", [
        ("limits", "Limits", 4, "The value a function approaches as the input gets close to a point."),
        ("derivative_definition", "Derivative as Rate of Change", 5, "The slope of a curve at a single point."),
        ("power_rule", "Power Rule", 5, "The shortcut for differentiating powers of x."),
        ("chain_rule", "Chain Rule", 5, "Differentiating a function inside another function."),
        ("optimization", "Finding Maxima & Minima", 5, "Using derivatives to find the best value."),
        ("partial_derivatives", "Partial Derivatives & Gradients", 5, "Rates of change when a function has several inputs."),
    ]),
    ("integrals", "Integrals", 5, "Adding up infinitely many tiny pieces.", [
        ("antiderivatives", "Antiderivatives", 5, "Running a derivative backwards."),
        ("area_under_curve", "Area Under a Curve", 5, "Approximating area with thinner and thinner rectangles."),
        ("fundamental_theorem", "Fundamental Theorem of Calculus", 5, "Why derivatives and integrals undo each other."),
    ]),
]

R, H = "requires", "helpful"
EDGES = [
    # ---- between trees / cross-tree ----
    ("fractions_decimals", "ratios_proportions", R),
    ("fractions_decimals", "linear_equations", R),
    ("fractions_decimals", "statistics", R),
    ("fractions_decimals", "probability", R),
    ("fractions_decimals", "exponents_roots", H),
    ("exponents_roots", "order_of_operations", H),
    ("variables_expressions", "linear_equations", R),
    ("variables_expressions", "functions", R),
    ("variables_expressions", "polynomials", R),
    ("variables_expressions", "sequences_series", R),
    ("sets_logic", "functions", H),
    ("sets_venn", "probability", H),
    ("mathematical_proof", "triangle_congruence", H),
    ("functions", "linear_functions", R),
    ("linear_equations", "linear_functions", R),
    ("proportional_relationships", "slope", R),
    ("linear_functions", "systems_of_equations", R),
    ("linear_equations", "systems_of_equations", R),
    ("exponents_roots", "polynomials", R),
    ("polynomials", "quadratic_functions", R),
    ("functions", "quadratic_functions", R),
    ("square_roots_radicals", "quadratic_formula", R),
    ("function_transformations", "parabolas", H),
    ("functions", "exponential_functions", R),
    ("exponent_rules", "exponential_functions", R),
    ("percent_change", "growth_decay", H),
    ("exponential_functions", "logarithms", R),
    ("inverse_functions", "logarithms", R),
    ("function_notation", "sequences_series", R),
    ("linear_functions", "arithmetic_sequences", H),
    ("exponential_functions", "geometric_sequences", H),
    ("ratios_proportions", "similar_triangles", R),
    ("square_roots_radicals", "pythagorean_theorem", R),
    ("linear_equations", "triangles", H),
    ("triangles", "trigonometry", R),
    ("functions", "trigonometry", R),
    ("linear_functions", "coordinate_geometry", R),
    ("pythagorean_theorem", "distance_formula", R),
    ("circle_equations", "unit_circle", H),
    ("pythagorean_theorem", "vector_magnitude", R),
    ("coordinate_geometry", "vectors", R),
    ("trigonometry", "vectors", H),
    ("vectors", "matrices", R),
    ("dot_product", "matrix_multiplication", R),
    ("systems_of_equations", "matrices", H),
    ("spread_std_dev", "normal_distribution", R),
    ("square_roots_radicals", "spread_std_dev", R),
    ("linear_functions", "scatter_plots_correlation", H),
    ("probability", "normal_distribution", H),
    ("functions", "derivatives", R),
    ("slope", "derivative_definition", R),
    ("polynomials", "power_rule", R),
    ("function_composition", "chain_rule", R),
    ("quadratic_functions", "optimization", H),
    ("vectors", "partial_derivatives", H),
    ("derivatives", "integrals", R),
    ("sigma_notation", "area_under_curve", R),
    ("power_rule", "antiderivatives", R),
    ("logarithms", "derivatives", H),
    # ---- order inside a tree ----
    ("equivalent_fractions", "fraction_operations", R),
    ("fraction_operations", "decimals_percents", R),
    ("unit_rates", "proportional_relationships", R),
    ("decimals_percents", "percent_change", R),
    ("exponent_rules", "scientific_notation", R),
    ("exponent_rules", "square_roots_radicals", H),
    ("order_of_operations", "distributive_property", R),
    ("distributive_property", "combining_like_terms", R),
    ("logical_statements", "mathematical_proof", R),
    ("multistep_equations", "linear_inequalities", R),
    ("multistep_equations", "literal_equations", R),
    ("function_notation", "domain_range", R),
    ("function_notation", "function_transformations", R),
    ("function_notation", "function_composition", R),
    ("function_composition", "inverse_functions", R),
    ("slope", "slope_intercept_form", R),
    ("angle_relationships", "similar_triangles", R),
    ("angle_relationships", "triangle_congruence", R),
    ("mean_median_mode", "spread_std_dev", R),
    ("basic_probability", "counting_combinatorics", H),
    ("basic_probability", "conditional_probability", R),
    ("conditional_probability", "bayes_theorem", R),
    ("polynomial_arithmetic", "factoring", R),
    ("factoring", "completing_the_square", H),
    ("completing_the_square", "quadratic_formula", R),
    ("distance_formula", "circle_equations", R),
    ("growth_decay", "compound_interest", R),
    ("log_rules", "solving_exponential_equations", R),
    ("arithmetic_sequences", "sigma_notation", H),
    ("right_triangle_trig", "unit_circle", R),
    ("radians", "unit_circle", R),
    ("unit_circle", "trig_identities", R),
    ("vector_magnitude", "dot_product", H),
    ("matrix_operations", "matrix_multiplication", R),
    ("matrix_multiplication", "determinants", R),
    ("determinants", "matrix_inverse", R),
    ("limits", "derivative_definition", R),
    ("derivative_definition", "power_rule", R),
    ("power_rule", "chain_rule", R),
    ("derivative_definition", "optimization", R),
    ("derivative_definition", "partial_derivatives", R),
    ("antiderivatives", "fundamental_theorem", R),
    ("area_under_curve", "fundamental_theorem", R),
]

nodes = []
for tid, name, lvl, desc, shrubs in TREES:
    nodes.append({"id": tid, "name": name, "forest": F, "kind": "tree", "parent": None,
                  "level": lvl, "description": desc, "resources": []})
    for sid, sname, slvl, sdesc in shrubs:
        nodes.append({"id": sid, "name": sname, "forest": F, "kind": "shrub", "parent": tid,
                      "level": slvl, "description": sdesc, "resources": []})
edges = [{"from": a, "to": b, "type": t} for a, b, t in EDGES]

json.dump(nodes, open("math_nodes.json", "w"), indent=2, ensure_ascii=False)
json.dump(edges, open("math_edges.json", "w"), indent=2, ensure_ascii=False)
print(len(TREES), "trees,", len(nodes) - len(TREES), "shrubs,", len(edges), "edges")